/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XpokyAmbulanceWlList {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLXpokyAmbulanceWlListElement extends Components.XpokyAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXpokyAmbulanceWlListElement: {
        prototype: HTMLXpokyAmbulanceWlListElement;
        new (): HTMLXpokyAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "xpoky-ambulance-wl-list": HTMLXpokyAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XpokyAmbulanceWlList {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "xpoky-ambulance-wl-list": XpokyAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "xpoky-ambulance-wl-list": LocalJSX.XpokyAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXpokyAmbulanceWlListElement>;
        }
    }
}
